Improve artenv robustness and add environment doctor

diff --git a/libexec/artenv-make b/libexec/artenv-make
--- a/libexec/artenv-make
+++ b/libexec/artenv-make
@@ -1,168 +1,185 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
-set -e
+script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
+# shellcheck source=/dev/null
+source "${script_dir}/util.sh"
 
-source util.sh
+print_var() {
+  local name="$1"
+  local value="$2"
+  printf '  %-22s %s\n' "${name}" "${value}"
+}
 
-currentdir=`pwd`
+confirm_yes() {
+  local prompt="$1"
+  local ans=""
 
-read -e -p "Enter the path to root> " rootsys
+  read -r -p "${prompt}" ans
+  case "${ans}" in
+    y|Y|yes|YES)
+      return 0
+      ;;
+    *)
+      return 1
+      ;;
+  esac
+}
 
-if [ -d "$rootsys" ]; then
-    rootsys=$(realpath $rootsys)
-else
-    echo "${rootsys} does not exist"
-    exit 1
-fi
+main() {
+  local currentdir
+  currentdir="$(pwd)"
 
-if [ ! -d "${rootsys}/bin" ]; then
-    echo "${rootsys}/bin does not exit"
-    exit 1
-fi
+  local rootsys=""
+  local yamlcpp=""
+  local yamllib=""
+  local yamlcmake=""
+  local artsrc=""
+  local artbld=""
+  local artsys=""
 
-if [ ! -d "${rootsys}/lib" ]; then
-    echo "${rootsys}/lib does not exit"
-    exit 1
-fi
+  local path="${PATH:-}"
+  local libpath="${LIBPATH:-}"
+  local shlib="${SHLIB_PATH:-}"
+  local ldlib="${LD_LIBRARY_PATH:-}"
+  local dyldlib="${DYLD_LIBRARY_PATH:-}"
+  local cmake_prefix_path="${CMAKE_PREFIX_PATH:-}"
 
-read -e -p "Enter the path to yaml-cpp> " yamlcpp
+  local version=""
+  local version_dir=""
 
-if [ -d "$yamlcpp" ]; then
-    # find lib
-    if [ -d "${yamlcpp}/lib" ]; then
-        yamllib=$(realpath "${yamlcpp}/lib");
-    elif [ -d "${yamlcpp}/lib64" ]; then
-        yamllib=$(realpath "${yamlcpp}/lib64");
-    else
-        echo "Could not find yaml-cpp library in ${yamlcpp}"
+  read -e -r -p "Enter the path to root> " rootsys
+  require_dir "${rootsys}"
+  rootsys="$(resolve_path "${rootsys}")"
+  require_dir "${rootsys}/bin"
+  require_dir "${rootsys}/lib"
+  require_file "${rootsys}/bin/root-config"
+
+  read -e -r -p "Enter the path to yaml-cpp> " yamlcpp
+  require_dir "${yamlcpp}"
+  yamlcpp="$(resolve_path "${yamlcpp}")"
+
+  if [[ -d "${yamlcpp}/lib" ]]; then
+    yamllib="$(resolve_path "${yamlcpp}/lib")"
+  elif [[ -d "${yamlcpp}/lib64" ]]; then
+    yamllib="$(resolve_path "${yamlcpp}/lib64")"
+  else
+    die "Could not find yaml-cpp library in ${yamlcpp}"
+  fi
+
+  if [[ -d "${yamllib}/cmake/yaml-cpp" ]]; then
+    yamlcmake="$(resolve_path "${yamllib}/cmake")"
+  elif [[ -d "${yamlcpp}/share/cmake/yaml-cpp" ]]; then
+    yamlcmake="$(resolve_path "${yamlcpp}/share/cmake")"
+  else
+    die "Could not find yaml-cpp CMake config in ${yamlcpp}"
+  fi
+
+  read -e -r -p "Enter the path to the source of artemis> " artsrc
+  require_dir "${artsrc}"
+  artsrc="$(resolve_path "${artsrc}")"
+
+  read -e -r -p "Enter the path to build directory> " artbld
+  [[ -n "${artbld}" ]] || die "build directory is empty"
+  artbld="$(resolve_path "${artbld}")"
+
+  read -e -r -p "Enter the install prefix> " artsys
+  [[ -n "${artsys}" ]] || die "install prefix is empty"
+  if [[ -e "${artsys}" ]]; then
+    artsys="$(resolve_path "${artsys}")"
+  else
+    mkdir -p -- "${artsys}"
+    artsys="$(resolve_path "${artsys}")"
+  fi
+
+  printf '%s\n' "Configuration:"
+  print_var "ROOTSYS" "${rootsys}"
+  print_var "YAML_CPP_LIB" "${yamllib}"
+  print_var "YAML_CPP_CMAKE" "${yamlcmake}"
+  print_var "ARTEMIS_SOURCE" "${artsrc}"
+  print_var "BUILD_DIR" "${artbld}"
+  print_var "INSTALL_PREFIX" "${artsys}"
+
+  if ! confirm_yes "OK? (y/N)> "; then
+    exit 0
+  fi
+
+  if [[ -d "${artbld}" ]]; then
+    if [[ -n "$(find "${artbld}" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
+      if confirm_yes "Build directory is not empty. Is it OK to erase the directory? (y/N)> "; then
+        [[ -n "${artbld}" ]] || die "build directory is empty"
+        [[ "${artbld}" != "/" ]] || die "refusing to erase /"
+        find "${artbld}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
+      else
         exit 1
+      fi
     fi
-    # find cmake config
-    if [ -d "${yamllib}/cmake/yaml-cpp" ]; then
-        yamlcmake=$(realpath "${yamllib}/cmake");
-    elif [ -d "${yamlcpp}/share/cmake/yaml-cpp" ]; then
-        yamlcmake=$(realpath "${yamlcpp}/share/cmake");
-    fi
-else
-    echo "${yamlcpp} does not exist"
-    exit 1
-fi
+  else
+    mkdir -p -- "${artbld}"
+  fi
 
-read -e -p "Enter the path to the source of artemis> " artsrc
+  if [[ -n "${ROOTSYS:-}" ]]; then
+    path="$(remove_path "${path}" "${ROOTSYS}/bin")"
+    libpath="$(remove_path "${libpath}" "${ROOTSYS}/lib")"
+    shlib="$(remove_path "${shlib}" "${ROOTSYS}/lib")"
+    ldlib="$(remove_path "${ldlib}" "${ROOTSYS}/lib")"
+    dyldlib="$(remove_path "${dyldlib}" "${ROOTSYS}/lib")"
+    cmake_prefix_path="$(remove_path "${cmake_prefix_path}" "${ROOTSYS}")"
+  fi
 
-if [ ! -d "$artsrc" ]; then
-    echo "${artsrc} does not exist"
-    exit 1
-fi
+  if [[ -n "${TARTSYS:-}" ]]; then
+    path="$(remove_path "${path}" "${TARTSYS}/bin")"
+    ldlib="$(remove_path "${ldlib}" "${TARTSYS}/lib")"
+    cmake_prefix_path="$(remove_path "${cmake_prefix_path}" "${TARTSYS}")"
+  fi
 
-read -e -p "Enter the path to build directory> " artbld
-read -e -p "Enter the install prefix> " artsys
+  if [[ -n "${YAML_CPP_LIB:-}" ]]; then
+    ldlib="$(remove_path "${ldlib}" "${YAML_CPP_LIB}")"
+  fi
 
-echo "Artemis will be built and installed to your environment with the following configulations."
-echo "- root: ${rootsys}"
-echo "- yaml-cpp: ${yamlcpp}"
-echo "- artemis:"
-echo "  - source directory: ${artsrc}"
-echo "  - build directory: ${artbld}"
-echo "  - install prefix: ${artsys}"
-read -p "OK? (y/N)> " ans
+  if [[ -n "${YAML_CPP_CMAKE:-}" ]]; then
+    cmake_prefix_path="$(remove_path "${cmake_prefix_path}" "${YAML_CPP_CMAKE}")"
+  fi
 
-case $ans in
-    [yY]*) ;;
-    *) exit 0;;
-esac
+  path="$(prepend_path "${path}" "${rootsys}/bin")"
+  ldlib="$(prepend_path "${ldlib}" "${yamllib}")"
+  ldlib="$(prepend_path "${ldlib}" "${rootsys}/lib")"
+  cmake_prefix_path="$(prepend_path "${cmake_prefix_path}" "${rootsys}")"
+  cmake_prefix_path="$(prepend_path "${cmake_prefix_path}" "${yamlcmake}")"
 
-if [ -d "$artbld" ]; then
-    if [ -n "$(ls $artbld)" ]; then
-        echo "${artbld} is not empty."
-        read -p "Is it OK to erase the directory? (y/N)> " ans
-        case $ans in
-            [yY]*) rm -rf $artbld/*;;
-            *) exit 0;;
-        esac
-    fi
-else
-    mkdir -p $artbld
-fi
+  export PATH="${path}"
+  export LIBPATH="${libpath}"
+  export SHLIB_PATH="${shlib}"
+  export LD_LIBRARY_PATH="${ldlib}"
+  export DYLD_LIBRARY_PATH="${dyldlib}"
+  export CMAKE_PREFIX_PATH="${cmake_prefix_path}"
 
-path=$PATH
-libpath=$LIBPATH
-shlib=$SHLIB_PATH
-ldlib=$LD_LIBRARY_PATH
-dyldlib=$DYLD_LIBRARY_PATH
-cmake_prefix_path=$CMAKE_PREFIX_PATH
+  cd "${artbld}" || exit 1
+  cmake "${artsrc}" -DCMAKE_INSTALL_PREFIX="${artsys}"
+  make -j"$(getconf _NPROCESSORS_ONLN)"
+  make install
+  cd "${currentdir}" || exit 1
 
-if [ -n "$ROOTSYS" ]; then
-    path=$(remove_path $path "${ROOTSYS}/bin")
-    libpath=$(remove_path $libpath "${ROOTSYS}/lib")
-    shlib=$(remove_path $shlib "${ROOTSYS}/lib")
-    ldlib=$(remove_path $ldlib "${ROOTSYS}/lib")
-    dyldlib=$(remove_path $dyldlib "${ROOTSYS}/lib")
-    cmake_prefix_path=$(remove_path $cmake_prefix_path "${ROOTSYS}")
-fi
+  if confirm_yes "Will you register this version to artenv? (y/N)> "; then
+    [[ -n "${ARTENV_ROOT:-}" ]] || die "ARTENV_ROOT is not set"
 
-if [ -n "$TARTSYS" ]; then
-    path=$(remove_path $path "${TARTSYS}/bin")
-    ldlib=$(remove_path $ldlib "${TARTSYS}/lib")
-    cmake_prefix_path=$(remove_path $cmake_prefix_path "${TARTSYS}")
-fi
+    read -r -p "Enter the version name> " version
+    [[ -n "${version}" ]] || die "version name is empty"
+    [[ "${version}" != */* ]] || die "version name must not contain /"
+    [[ "${version}" != "." && "${version}" != ".." ]] || die "invalid version name"
 
-if [ -n "$YAML_CPP_LIB" ]; then
-    ldlib=$(remove_path $ldlib "$YAML_CPP_LIB")
-fi
+    version_dir="${ARTENV_ROOT}/versions/${version}"
+    [[ ! -e "${version_dir}" ]] || die "${version} already exists"
 
-if [ -n "$YAML_CPP_CMAKE" ]; then
-    cmake_prefix_path=$(remove_path $cmake_prefix_path "${YAML_CPP_CMAKE}")
-fi
+    ensure_dir "${ARTENV_ROOT}/versions"
+    mkdir -p -- "${version_dir}"
+    ln -s -- "${artsys}" "${version_dir}/artsys"
+    ln -s -- "${rootsys}" "${version_dir}/rootsys"
+    ln -s -- "${yamllib}" "${version_dir}/yamllib"
+    ln -s -- "${yamlcmake}" "${version_dir}/yamlcmake"
 
-path=$(prepend_path "$path" "${rootsys}/bin")
-libpath=$(prepend_path "$libpath" "${rootsys}/lib")
-shlib=$(prepend_path "$shlib" "${rootsys}/lib")
-ldlib=$(prepend_path "$ldlib" "$yamllib")
-ldlib=$(prepend_path "$ldlib" "${rootsys}/lib")
-dyldlib=$(prepend_path "$dyldlib" "${rootsys}/lib")
-cmake_prefix_path=$(prepend_path $cmake_prefix_path "${rootsys}")
-cmake_prefix_path=$(prepend_path $cmake_prefix_path "${yamlcmake}")
+    printf '%s was registered\n' "${version}"
+  fi
+}
 
-PATH=$path
-LIBPATH=$libpath
-SHLIB_PATH=$shlib
-LD_LIBRARY_PATH=$ldlib
-DYLD_LIBRARY_PATH=$dyldlib
-CMAKE_PREFIX_PATH=$cmake_prefix_path
-
-cd $artbld
-cmake $artsrc -DCMAKE_INSTALL_PREFIX="${artsys}"
-make -j4
-make install
-
-cd $currentdir
-echo "artemis is built and installed to ${artsys}"
-
-while true; do
-    read -p "Will you register this version to artenv? (y/N)> " ans
-    case $ans in
-        [yY]*)
-            read -p "Enter the version name>" version
-            version_dir="${ARTENV_ROOT}/versions/${version}"
-
-            if [ -d "${version_dir}" ]; then
-                echo "${version} already exists"
-                continue
-            fi
-
-            mkdir -p $version_dir
-            ln -s $artsys ${version_dir}/artsys
-            ln -s $rootsys ${version_dir}/rootsys
-            ln -s $yamllib ${version_dir}/yamllib
-            ln -s $yamlcmake ${version_dir}/yamlcmake
-            echo "${version} was registered"
-            break
-            ;;
-
-        *)
-            break
-            ;;
-    esac
-done
-
+main "$@"
diff --git a/libexec/artenv-register-env b/libexec/artenv-register-env
--- a/libexec/artenv-register-env
+++ b/libexec/artenv-register-env
@@ -1,69 +1,107 @@
 #!/usr/bin/env bash
 
-set -e
+set -euo pipefail
 
-if [ $# != 1 ]; then
-    echo "artenv register-env <env-name>"
-    exit 1
-fi
+script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
+# shellcheck source=/dev/null
+source "${script_dir}/util.sh"
 
-env=$1
-env_dir="${ARTENV_ROOT}/envs/${env}"
+main() {
+  [[ -n "${ARTENV_ROOT:-}" ]] || die "ARTENV_ROOT is not set"
+  [[ $# -eq 1 ]] || die "usage: artenv register-env <env>"
 
-if [ -d "$env_dir" ]; then
-    echo "${env} already exists"
-    exit 1
-fi
+  local env_name="$1"
+  local env_dir="${ARTENV_ROOT}/envs/${env_name}"
+  local versions_dir="${ARTENV_ROOT}/versions"
+  local tmp_dir
 
-versions_dir="${ARTENV_ROOT}/versions"
-if [ -d "$versions_dir" ]; then
-    versions_dir="$(realpath $versions_dir)"
-fi
-versions_dir_entries=("$versions_dir"/*)
-echo "Select the artemis version"
-select version in "${versions_dir_entries[@]##*/}"; do
-    if [ ! -z $version ]; then
-        break ;
+  local work=""
+  local git_repos=""
+  local use_artlogin=""
+  local version_name=""
+  local version_dir=""
+  local template_artlogin="${ARTENV_ROOT}/libexec/artlogin.sh"
+
+  [[ -n "${env_name}" ]] || die "environment name is empty"
+  [[ "${env_name}" != */* ]] || die "environment name must not contain /"
+  [[ "${env_name}" != "." && "${env_name}" != ".." ]] || die "invalid environment name"
+  [[ ! -e "${env_dir}" ]] || die "${env_name} already exists"
+
+  require_dir "${versions_dir}"
+
+  local -a version_entries=()
+  local -a version_names=()
+  local entry
+
+  shopt -s nullglob
+  version_entries=("${versions_dir}"/*)
+  shopt -u nullglob
+
+  [[ ${#version_entries[@]} -gt 0 ]] || die "no artemis versions are registered"
+
+  for entry in "${version_entries[@]}"; do
+    [[ -d "${entry}" ]] || continue
+    version_names+=("$(basename "${entry}")")
+  done
+
+  [[ ${#version_names[@]} -gt 0 ]] || die "no artemis versions are registered"
+
+  echo "Select the artemis version"
+  select version_name in "${version_names[@]}"; do
+    if [[ -n "${version_name:-}" ]]; then
+      version_dir="${versions_dir}/${version_name}"
+      break
     else
-        echo "Wrong selection"
+      echo "Wrong selection"
     fi
-done
+  done
 
-echo "${version} was selected"
-version="${versions_dir}/${version}"
+  require_dir "${version_dir}"
+  echo "${version_name} was selected"
 
-read -e -p "Enter the path to working directory> " work
-if [ -d "$work" ]; then
-    work="$(realpath $work)"
-else
-    echo "${work} dose not exist"
-    exit 1
-fi
+  read -e -r -p "Enter the path to working directory> " work
+  require_dir "${work}"
+  work="$(resolve_path "${work}")"
 
-while true; do
-    read -e -p "Use artlogin? (y/n)> " use_artlogin
-    case $use_artlogin in
-        y)
-            mkdir -p $env_dir
-            read -e -p "Enter the path to git repos (required)> " git_repos
-            ln -s $version ${env_dir}/version
-            ln -s $work ${env_dir}/work
-            ln -s $git_repos ${env_dir}/git_repos
-            cp $ARTENV_ROOT/libexec/artlogin.sh ${env_dir}/
-            break
-            ;;
-        n)
-            mkdir -p $env_dir
-            read -e -p "Enter the path to git repos (optional)> " git_repos
-            ln -s $version ${env_dir}/version
-            ln -s $work ${env_dir}/work
-            if [  $git_repos ]; then
-                ln -s $git_repos ${env_dir}/git_repos
-            fi
-            break
-            ;;
+  while true; do
+    read -e -r -p "Use artlogin? (y/n)> " use_artlogin
+    case "${use_artlogin}" in
+      y|Y)
+        require_file "${template_artlogin}"
+        read -e -r -p "Enter the path to git repos (required)> " git_repos
+        [[ -n "${git_repos}" ]] || die "git repos is required when artlogin is enabled"
+        break
+        ;;
+      n|N)
+        read -e -r -p "Enter the path to git repos (optional)> " git_repos
+        break
+        ;;
+      *)
+        echo "Please answer y or n"
+        ;;
     esac
-done
+  done
 
-echo "${env} was registered"
+  ensure_dir "${ARTENV_ROOT}/envs"
+  tmp_dir="$(mktemp -d "${ARTENV_ROOT}/envs/.tmp.${env_name}.XXXXXX")"
+  trap 'rm -rf -- "${tmp_dir}"' EXIT
+
+  ln -s -- "${version_dir}" "${tmp_dir}/version"
+  ln -s -- "${work}" "${tmp_dir}/work"
+
+  if [[ -n "${git_repos:-}" ]]; then
+    printf '%s\n' "${git_repos}" > "${tmp_dir}/git_repos"
+  fi
+
+  if [[ "${use_artlogin}" == "y" || "${use_artlogin}" == "Y" ]]; then
+    cp -- "${template_artlogin}" "${tmp_dir}/artlogin.sh"
+  fi
+
+  mv -- "${tmp_dir}" "${env_dir}"
+  trap - EXIT
+
+  printf '%s was registered\n' "${env_name}"
+}
+
+main "$@"
 
